/** 34 tỉnh/thành phố trực thuộc trung ương theo NQ 202/2025/QH15 */
export const VIETNAM_PROVINCES: string[] = [
  'TP. Hà Nội',
  'TP. Hồ Chí Minh',
  'TP. Hải Phòng',
  'TP. Đà Nẵng',
  'TP. Cần Thơ',
  'TP. Huế',
  'An Giang',
  'Bắc Ninh',
  'Cao Bằng',
  'Cà Mau',
  'Điện Biên',
  'Đắk Lắk',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Tĩnh',
  'Hưng Yên',
  'Khánh Hòa',
  'Lai Châu',
  'Lạng Sơn',
  'Lào Cai',
  'Nam Định',
  'Nghệ An',
  'Phú Thọ',
  'Phú Yên',
  'Quảng Bình',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Sơn La',
  'Tây Ninh',
  'Thanh Hóa',
  'Thái Nguyên',
  'Tuyên Quang',
  'Vĩnh Long',
];
